import Head from 'next/head'
import CalenderSection from '../components/CalenderSection'
import Footer from '../components/Footer'
import HeroSection from '../components/HeroSection'
import OptionsSection from '../components/OptionsSection'
import PrestationSection from '../components/PrestationSection'
import ReservationSection from '../components/ReservationSection'
import TypeOfVehicleSection from '../components/TypeOfVehicleSection'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeroSection />
        <TypeOfVehicleSection />
        <PrestationSection />
        <OptionsSection />
        <CalenderSection />
        <ReservationSection />
        <Footer />
      </main>
    </>
  )
}
